name: Pruebas unitarias y funcionales

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4      

      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Cargar esquema de la base de datos
        run: |
          psql -h localhost -U postgres -d testdb -f scripts.sql  2>&1 | tee sql_log.txt 
        env:
          PGPASSWORD: postgres

      - name: Test table 1 creation
        run: |
          if [ $(grep -c "CREATE TABLE" sql_log.txt) -lt 1 ]; then
            echo "Menos de una tabla creada."
            exit 1
          else
            echo "Un punto por la creación de una tabla."
          fi          

      - name: Test insertions of 3 records
        run: |
          if [ $(grep -c "INSERT 0 3" sql_log.txt) -lt 1 ]; then
            echo "No se encontró la inserción de 3 registros."
            exit 1
          else
            echo "Un punto por la inserción de tres registros."
          fi     

      - name: Test index creation
        run: |
          if [ $(grep -c "CREATE INDEX" sql_log.txt) -lt 1 ]; then
            echo "Índice no creado."
            exit 1
          else
            echo "Un punto por la creación de un índice."
          fi

      - name: Test table 2 creation
        run: |
          if [ $(grep -c "CREATE TABLE" sql_log.txt) -lt 2 ]; then
            echo "Menos de dos tablas creadas."
            exit 1
          else
            echo "Un punto por la creación de la segunda tabla."
          fi                      

      - name: Test insertions of 2 records
        run: |
          if [ $(grep -c "INSERT 0 2" sql_log.txt) -lt 1 ]; then
            echo "Menos de una inserción de dos registros."
            exit 1
          else
            echo "Un punto por la inserción de dos registros."
          fi    
          

      - name: Test table 3 creation
        run: |
          if [ $(grep -c "CREATE TABLE" sql_log.txt) -lt 3 ]; then
            echo "Menos de tres tablas creadas."
            exit 1
          else
            echo "Un punto por la creación de la tercera tabla."
          fi                      

      - name: Test insertions of 3 records
        run: |
          if [ $(grep -c "INSERT 0 3" sql_log.txt) -lt 2 ]; then
            echo "Menos de dos inserciones de dos registros."
            exit 1
          else
            echo "Un punto por la inserción de tres registros por segunda vez."
          fi    
                    
      - name: Test query 1
        run: |
          if [ $(grep -c "row" sql_log.txt) -lt 1 ]; then
            echo "Menos de una consulta o sin renglones."
            exit 1
          else
            echo "Un punto por la primera consulta."
          fi 
                
      - name: Test query 2
        run: |
          if [ $(grep -c "row" sql_log.txt) -lt 2 ]; then
            echo "Menos de dos consultas."
            exit 1
          else
            echo "Un punto por la segunda consulta."
          fi 
                  
      - name: Test query 3
        run: |
          if [ $(grep -c "row" sql_log.txt) -lt 3 ]; then
            echo "Menos de tres consultas."
            exit 1
          else
            echo "Un punto por la tercera consulta."
          fi 
                            